# Generated by Django 2.2.9 on 2020-02-27 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='uploaded_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
